# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20171110_0333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PusherableExample',
        ),
    ]
