# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extended_user',
            name='years',
        ),
        migrations.AddField(
            model_name='extended_user',
            name='user',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
