# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20171214_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=400)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='myApp.Post')),
            ],
        ),
    ]
